### ISSUE TITLE
Wearlink fabrication

### ISSUE THREAD

**Issue by zjobra** [dijkstrw/wearlink#1]
I've uploaded wearlink to pcbhubs for manufacturing order
https://pcbhubs.com/newpcb/16010209055f6da3e9c1e43

**Comment by dijkstrw** [comment]
Good to hear you are interested in this project.

Are you aware of the [new version](https://github.com/dijkstrw/wearlink_nrf58122) of this board that uses BLE instead of a wired connection? This versions' wired connection always broke for me over time due to repeated wire movements while wearing the coat.
